<?xml version="1.0" encoding="utf-8"?>
<Database Name="fngrdb2012" Class="DB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=fngrdb2012;User ID=sa" SettingsObjectName="KDB.Properties.Settings" SettingsPropertyName="KQConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblLeave" Member="tblLeave">
    <Type Name="tblLeave">
      <Column Name="LeaveID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LeaveType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LeaveRemark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LeaveBegin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LeaveEnd" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblPerson_tblLeave" Member="tblPerson" ThisKey="PersonID" Type="tblPerson" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPerson" Member="tblPerson">
    <Type Name="tblPerson">
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TmID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblPerson_tblLeave" Member="tblLeave" OtherKey="PersonID" Type="tblLeave" />
      <Association Name="tblPerson_tblExWork" Member="tblExWork" OtherKey="PersonID" Type="tblExWork" />
      <Association Name="tblTM_tblPerson" Member="tblTM" ThisKey="TmID" Type="tblTM" IsForeignKey="true" />
      <Association Name="tblGroup_tblPerson" Member="tblGroup" ThisKey="GroupID" Type="tblGroup" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tblTimeDefine" Member="tblTimeDefine">
    <Type Name="tblTimeDefine">
      <Column Name="TimeDefineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartTime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DayOffset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsCrossDay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WorkDefineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblTmData" Member="tblTmData">
    <Type Name="tblTmData">
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TmDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TmID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TmDataDT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tblDevice_tblTmData" Member="tblDevice" ThisKey="DeviceID" Type="tblDevice" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tblTM_tblTmData" Member="tblTM" ThisKey="TmID" Type="tblTM" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDevice" Member="tblDevice">
    <Type Name="tblDevice">
      <Column Name="DeviceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeviceAddress" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeviceType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeviceRemark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DeviceExtend" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="tblDevice_tblTmData" Member="tblTmData" OtherKey="DeviceID" Type="tblTmData" />
      <Association Name="tblStation_tblDevice" Member="tblStation" ThisKey="StationID" Type="tblStation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblStation" Member="tblStation">
    <Type Name="tblStation">
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StationOrdinal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StationRemark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="StationCPConfig" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="tblStation_tblDevice" Member="tblDevice" OtherKey="StationID" Type="tblDevice" />
      <Association Name="tblStation_tblGroupStation" Member="tblGroupStation" OtherKey="StationID" Type="tblGroupStation" />
    </Type>
  </Table>
  <Table Name="dbo.tblExWork" Member="tblExWork">
    <Type Name="tblExWork">
      <Column Name="ExWorkID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExWorkName" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="ExWorkBegin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExWorkEnd" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExWorkRemark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="tblPerson_tblExWork" Member="tblPerson" ThisKey="PersonID" Type="tblPerson" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTM" Member="tblTM">
    <Type Name="tblTM">
      <Column Name="TmID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TmSN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TmRemark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="tblTM_tblPerson" Member="tblPerson" OtherKey="TmID" Type="tblPerson" />
      <Association Name="tblTM_tblTmData" Member="tblTmData" OtherKey="TmID" Type="tblTmData" />
    </Type>
  </Table>
  <Table Name="dbo.tblGroupStation" Member="tblGroupStation">
    <Type Name="tblGroupStation">
      <Column Name="GroupStationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tblStation_tblGroupStation" Member="tblStation" ThisKey="StationID" Type="tblStation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tblGroup_tblGroupStation" Member="tblGroup" ThisKey="GroupID" Type="tblGroup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblGroup" Member="tblGroup">
    <Type Name="tblGroup">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkDefineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupSpecialStation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tblGroup_tblPerson" Member="tblPerson" OtherKey="GroupID" Type="tblPerson" />
      <Association Name="tblGroup_tblGroupStation" Member="tblGroupStation" OtherKey="GroupID" Type="tblGroupStation" />
      <Association Name="tblWorkDefine_tblGroup" Member="tblWorkDefine" ThisKey="WorkDefineID" Type="tblWorkDefine" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblWorkDefine" Member="tblWorkDefine">
    <Type Name="tblWorkDefine">
      <Column Name="WorkDefineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WorkDefineName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkDefineContext" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="tblWorkDefine_tblGroup" Member="tblGroup" OtherKey="WorkDefineID" Type="tblGroup" />
    </Type>
  </Table>
</Database>