//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdgk.GRCommon {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphPaneConfigStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphPaneConfigStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xdgk.GRCommon.GraphPaneConfigStrings", typeof(GraphPaneConfigStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string DateTimeAxisTitle {
            get {
                return ResourceManager.GetString("DateTimeAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量(m3/h) 的本地化字符串。
        /// </summary>
        internal static string FluxAxisTitle {
            get {
                return ResourceManager.GetString("FluxAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 流量曲线 {1} ~ {2} 的本地化字符串。
        /// </summary>
        internal static string FluxTitleFormat {
            get {
                return ResourceManager.GetString("FluxTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热量(GJ) 的本地化字符串。
        /// </summary>
        internal static string HeatAxisTitle {
            get {
                return ResourceManager.GetString("HeatAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 热量曲线 {1} ~ {2} 的本地化字符串。
        /// </summary>
        internal static string HeatTitleFormat {
            get {
                return ResourceManager.GetString("HeatTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室外温度(℃) 的本地化字符串。
        /// </summary>
        internal static string OTAxisTitle {
            get {
                return ResourceManager.GetString("OTAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 室外温度曲线 {1} ~ {2} 的本地化字符串。
        /// </summary>
        internal static string OTTitleFormat {
            get {
                return ResourceManager.GetString("OTTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力(MPa) 的本地化字符串。
        /// </summary>
        internal static string PressAxisTitle {
            get {
                return ResourceManager.GetString("PressAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 压力曲线 {1} ~ {2} 的本地化字符串。
        /// </summary>
        internal static string PressTitleFormat {
            get {
                return ResourceManager.GetString("PressTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度(℃) 的本地化字符串。
        /// </summary>
        internal static string TemperatureAxisTitle {
            get {
                return ResourceManager.GetString("TemperatureAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 温度曲线 {1} ~ {2} 的本地化字符串。
        /// </summary>
        internal static string TemperatureTitleFormat {
            get {
                return ResourceManager.GetString("TemperatureTitleFormat", resourceCulture);
            }
        }
    }
}
