//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNGRQRC {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FNGRQRC.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;全部&gt; 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 和丰供热数据查询 的本地化字符串。
        /// </summary>
        internal static string AppText {
            get {
                return ResourceManager.GetString("AppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要退出吗? 的本地化字符串。
        /// </summary>
        internal static string AreYouExit {
            get {
                return ResourceManager.GetString("AreYouExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次回压 的本地化字符串。
        /// </summary>
        internal static string BP1 {
            get {
                return ResourceManager.GetString("BP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次回压 的本地化字符串。
        /// </summary>
        internal static string BP2 {
            get {
                return ResourceManager.GetString("BP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次回温 的本地化字符串。
        /// </summary>
        internal static string BT1 {
            get {
                return ResourceManager.GetString("BT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次回温 的本地化字符串。
        /// </summary>
        internal static string BT2 {
            get {
                return ResourceManager.GetString("BT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗热量 的本地化字符串。
        /// </summary>
        internal static string CostHeat {
            get {
                return ResourceManager.GetString("CostHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能同时绘制 {0} 条曲线 的本地化字符串。
        /// </summary>
        internal static string CurveCountEnough {
            get {
                return ResourceManager.GetString("CurveCountEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要同时绘制 {0} 条曲线 的本地化字符串。
        /// </summary>
        internal static string CurveCountNotEnough {
            get {
                return ResourceManager.GetString("CurveCountNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电量曲线 的本地化字符串。
        /// </summary>
        internal static string EMCurve {
            get {
                return ResourceManager.GetString("EMCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电量数据 的本地化字符串。
        /// </summary>
        internal static string EMData {
            get {
                return ResourceManager.GetString("EMData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电量 的本地化字符串。
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量 的本地化字符串。
        /// </summary>
        internal static string Flux {
            get {
                return ResourceManager.GetString("Flux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量(m3/h) 的本地化字符串。
        /// </summary>
        internal static string FluxAxisTitle {
            get {
                return ResourceManager.GetString("FluxAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次供压 的本地化字符串。
        /// </summary>
        internal static string GP1 {
            get {
                return ResourceManager.GetString("GP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次供压 的本地化字符串。
        /// </summary>
        internal static string GP2 {
            get {
                return ResourceManager.GetString("GP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警数据 的本地化字符串。
        /// </summary>
        internal static string GRAlarmData {
            get {
                return ResourceManager.GetString("GRAlarmData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供热数据 的本地化字符串。
        /// </summary>
        internal static string GRData {
            get {
                return ResourceManager.GetString("GRData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新供热数据 的本地化字符串。
        /// </summary>
        internal static string GRDataLast {
            get {
                return ResourceManager.GetString("GRDataLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次供温 的本地化字符串。
        /// </summary>
        internal static string GT1 {
            get {
                return ResourceManager.GetString("GT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次供温 的本地化字符串。
        /// </summary>
        internal static string GT2 {
            get {
                return ResourceManager.GetString("GT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次瞬时热量 的本地化字符串。
        /// </summary>
        internal static string H1 {
            get {
                return ResourceManager.GetString("H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次瞬时流量 的本地化字符串。
        /// </summary>
        internal static string I1 {
            get {
                return ResourceManager.GetString("I1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补水瞬时流量 的本地化字符串。
        /// </summary>
        internal static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室外温度 的本地化字符串。
        /// </summary>
        internal static string OT {
            get {
                return ResourceManager.GetString("OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力 的本地化字符串。
        /// </summary>
        internal static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力曲线 的本地化字符串。
        /// </summary>
        internal static string PressCurve {
            get {
                return ResourceManager.GetString("PressCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补水曲线 的本地化字符串。
        /// </summary>
        internal static string RecruitCurve {
            get {
                return ResourceManager.GetString("RecruitCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 补水数据 的本地化字符串。
        /// </summary>
        internal static string RecruitData {
            get {
                return ResourceManager.GetString("RecruitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据行数不能大于 {0} 的本地化字符串。
        /// </summary>
        internal static string RowCountOutOfRange {
            get {
                return ResourceManager.GetString("RowCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度曲线 的本地化字符串。
        /// </summary>
        internal static string TempCurve {
            get {
                return ResourceManager.GetString("TempCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度 的本地化字符串。
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巡更数据 的本地化字符串。
        /// </summary>
        internal static string XGData {
            get {
                return ResourceManager.GetString("XGData", resourceCulture);
            }
        }
    }
}
