//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace fnbx {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fnbx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 权限不够, 不能创建报修单 的本地化字符串。
        /// </summary>
        internal static string CannotCreateMT {
            get {
                return ResourceManager.GetString("CannotCreateMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能删除报修单 的本地化字符串。
        /// </summary>
        internal static string CannotDeleteMT {
            get {
                return ResourceManager.GetString("CannotDeleteMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能修改报修单 的本地化字符串。
        /// </summary>
        internal static string CannotEditMT {
            get {
                return ResourceManager.GetString("CannotEditMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能修改状态 的本地化字符串。
        /// </summary>
        internal static string CannotModifyMTStatus {
            get {
                return ResourceManager.GetString("CannotModifyMTStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址不能为空 的本地化字符串。
        /// </summary>
        internal static string ITAddressEmpty {
            get {
                return ResourceManager.GetString("ITAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人不能为空 的本地化字符串。
        /// </summary>
        internal static string ITNameEmpty {
            get {
                return ResourceManager.GetString("ITNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话不能为空 的本地化字符串。
        /// </summary>
        internal static string ITPhoneEmpty {
            get {
                return ResourceManager.GetString("ITPhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修时间不能为过去的时间 的本地化字符串。
        /// </summary>
        internal static string MTBeginOld {
            get {
                return ResourceManager.GetString("MTBeginOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容不能为空 的本地化字符串。
        /// </summary>
        internal static string MTContentEmpty {
            get {
                return ResourceManager.GetString("MTContentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时间不能为过去的时间 的本地化字符串。
        /// </summary>
        internal static string MTTimeoutOld {
            get {
                return ResourceManager.GetString("MTTimeoutOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离超时时间还有 {0} 的本地化字符串。
        /// </summary>
        internal static string RemainTimespan {
            get {
                return ResourceManager.GetString("RemainTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成内容不能为空 的本地化字符串。
        /// </summary>
        internal static string RPContentEmpty {
            get {
                return ResourceManager.GetString("RPContentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成时间必须大于接单时间 的本地化字符串。
        /// </summary>
        internal static string RPEndDTMustGreaterReceivedDT {
            get {
                return ResourceManager.GetString("RPEndDTMustGreaterReceivedDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成时间必须小于超时时间 的本地化字符串。
        /// </summary>
        internal static string RPEndDTMustLessTimeoutDT {
            get {
                return ResourceManager.GetString("RPEndDTMustLessTimeoutDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成人不能为空 的本地化字符串。
        /// </summary>
        internal static string RPWorkerEmpty {
            get {
                return ResourceManager.GetString("RPWorkerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选中一条记录 的本地化字符串。
        /// </summary>
        internal static string SelectMTFirst {
            get {
                return ResourceManager.GetString("SelectMTFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择新状态 的本地化字符串。
        /// </summary>
        internal static string SelectNewStatus {
            get {
                return ResourceManager.GetString("SelectNewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除吗? 的本地化字符串。
        /// </summary>
        internal static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已超时 的本地化字符串。
        /// </summary>
        internal static string Timeouted {
            get {
                return ResourceManager.GetString("Timeouted", resourceCulture);
            }
        }
    }
}
